tasks:
  - before: |
      sudo apt-get install -y cowsay
    init: |
      cowsay "Installing AWS CLI"
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cowsay "Installing Azure CLI"
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      cowsay "Installing GCP CLI"
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-363.0.0-linux-x86_64.tar.gz
      tar -zxf google-cloud-sdk-*
      ./google-cloud-sdk/install.sh
      go get github.com/spf13/cobra/cobra
      go build
      go get && go build ./... && go test ./...
    command: |
      ./terraform-provider-ublob

vscode:
  extensions:
    - golang.go
