tasks:
  - before: |
      echo "Installing cowsay"
      sudo apt-get install -y cowsay
    init: |
      cowsay "Installing AWS CLI"
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      cowsay "Installing Azure CLI"
      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      cowsay "Installing GCP CLI"
      curl https://sdk.cloud.google.com > install.sh
      bash install.sh --disable-prompts

      cowsay "Installing Terraform"
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform

      go get github.com/spf13/cobra/cobra
      go build
      go get && go build ./... && go test ./...
    command: |
      ./terraform-provider-ublob

vscode:
  extensions:
    - golang.go
    - hashicorp.terraform
